{{- range .Values.wordpressSites }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-{{ .name }}
  labels:
    app: wordpress-{{ .name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-{{ .name }}
  template:
    metadata:
      labels:
        app: wordpress-{{ .name }}
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.4-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: {{ $.Values.mysql.user | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ $.Values.mysql.password | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ $.Values.mysql.database | quote }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
{{- end }}
