name: Helm Lint (Reusable)

on:
  workflow_call:
    inputs:
      chart-path:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm chart
        run: helm lint ${{ inputs.chart-path }}
