name: Lint all markdown files

on:
  push:
    paths:
      - '*.md'  # Trigger only when a file with the extension `.md` is modified
      - '**/*.md'
    branches: [main]  # Trigger on pushes to the main branch
  pull_request:
    paths:
      - '*.md'  # Trigger only when Markdown.md is modified
      - '**/*.md'
    branches: [main]  # Also trigger on pull requests to main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - uses: actions/setup-node@v3
        with:
          node-version: 16  # Use Node.js version 16
      - run: npm install -g markdownlint-cli  # Install markdownlint-cli
      - run: markdownlint . --config .markdownlint.yml  # Lint the markdown files